// Generated by scripts/generate-metal-kernels.py. Source SHA-256: 36813e777d0820274f3d2e4f52811f7701e337c509584778ea467285e42e0102
#include <metal_stdlib>
using namespace metal;
// Full-width high product from exact 32-bit limbs. No floating-point arithmetic.
inline ulong metal_mul_hi(ulong a, ulong b) {
    ulong p0 = ulong(uint(a)) * uint(b);
    ulong p1 = ulong(uint(a)) * uint(b >> 32);
    ulong p2 = ulong(uint(a >> 32)) * uint(b);
    ulong p3 = ulong(uint(a >> 32)) * uint(b >> 32);
    ulong carry = (p0 >> 32) + ulong(uint(p1)) + ulong(uint(p2));
    return p3 + (p1 >> 32) + (p2 >> 32) + (carry >> 32);
}

#define NEG_ORDER 0xFFFFFFFFUL
#define GP        0xFFFFFFFF00000001UL
inline ulong gl_reduce128(ulong lo,ulong hi){ uint hh=(uint)(hi>>32),hl=(uint)(hi&0xFFFFFFFFUL);
 ulong t0=lo-(ulong)hh; if(lo<(ulong)hh)t0-=NEG_ORDER; ulong t1=(ulong)hl*NEG_ORDER; ulong t2=t0+t1; if(t2<t0)t2+=NEG_ORDER; return t2; }
inline ulong gl_mul(ulong a,ulong b){ return gl_reduce128(a*b, metal_mul_hi(a,b)); }
inline ulong gl_add(ulong a,ulong b){ ulong s=a+b; ulong o1=(s<a)?NEG_ORDER:0UL; ulong s2=s+o1; ulong o2=(s2<s)?NEG_ORDER:0UL; return s2+o2; }
inline ulong gl_neg(ulong b){ ulong c=(b>=GP)?(b-GP):b; return c==0UL?0UL:(GP-c); }
inline ulong gl_sub(ulong a,ulong b){ return gl_add(a, gl_neg(b)); }
inline ulong gl_canon(ulong c){ return (c>=GP)?(c-GP):c; }
inline ulong gl_pow(ulong b,ulong e){ ulong r=1UL; while(e){ if(e&1UL)r=gl_mul(r,b); b=gl_mul(b,b); e>>=1;} return r; }
inline uint brev(uint x, uint bits){ uint r=0; for(uint i=0;i<bits;i++){ r=(r<<1)|(x&1u); x>>=1; } return r; }

// ---- tiled NTT: radix-2 DIT, `lt` stages per kernel launch in local memory ----
// The NTT is MEMORY-bound: one butterfly stage per launch means a full global round-trip per stage.
// Here one workgroup owns a TILE=2^lt-row × C=2^log_c-column tile — rows r(t) = hi<<(s0+lt) | t<<s0 | lo
// (t = 0..TILE) are exactly the rows whose stage-(s0+1 ..= s0+lt) butterflies interconnect (those stages
// pair rows differing in bits [s0, s0+lt)) — for C consecutive columns (coalesced global runs). It loads
// the tile once, runs the `lt` stages against local memory (barrier between stages), and stores once:
// ONE global round-trip for `lt` stages. The twiddle for stage s = s0+k at row r, j = r mod 2^(s-1),
// splits as w_s^j = w_s^lo · w_k^(t mod 2^(k-1)) — p3's generators form one squaring chain
// (gen(s)^(2^s0) = gen(s-s0), forward and inverse alike), so the per-stage generators `wlens` suffice;
// no twiddle table (a table would ADD memory traffic; gl_pow is compute, hidden behind the loads).
// fuse_bitrev (first group only, s0 = 0): load from bit-reversed source rows, fusing the bit-reversal
// pass — requires in != out. store_brev (last group of a forward NTT): store row r to row brev(r),
// emitting the matrix directly in p3's bit-reversed storage order (kills the CPU re-permutation pass);
// scattered stores land outside the workgroup's own rows, so it too requires in != out. Groups with
// neither flag pass in == out (in-place is safe: a workgroup touches only its own rows). The store also
// fuses the elementwise tails so they cost no extra pass:
//   out = canon?(x · post_c · post_b^row)   — post_c = post_b = 1, do_canon = 0 for a plain store;
// the iDFT's last group passes post_c = 1/h, post_b = coset shift; a forward NTT's last group canons.
kernel void ntt_tile(
    device const ulong* in [[buffer(0)]],
    device ulong* out [[buffer(1)]],
    constant uint& w [[buffer(2)]],
    constant uint& h [[buffer(3)]],
    constant uint& s0 [[buffer(4)]],
    constant uint& lt [[buffer(5)]],
    constant uint& log_c [[buffer(6)]],
    constant uint& fuse_bitrev [[buffer(7)]],
    constant uint& log_h [[buffer(8)]],
    constant uint& do_canon [[buffer(9)]],
    constant uint& store_brev [[buffer(10)]],
    constant ulong& post_c [[buffer(11)]],
    constant ulong& post_b [[buffer(12)]],
    device const ulong* wlens [[buffer(13)]],
    threadgroup ulong* tile [[threadgroup(0)]],
    uint _gid [[thread_position_in_grid]],
    uint _lid [[thread_index_in_threadgroup]],
    uint _group [[threadgroup_position_in_grid]],
    uint _gsize [[threads_per_threadgroup]]) {
  const uint C=1u<<log_c, lid=_lid, wg=_gsize;
  const uint tiles=h>>lt, g=(uint)_group;
  const uint tidx=g%tiles, cg=g/tiles;
  const uint lo=tidx&((1u<<s0)-1u), hi=tidx>>s0;
  const uint row0=(hi<<(s0+lt))|lo, col0=cg<<log_c;
  const uint n_el=(1u<<lt)<<log_c;
  for(uint e=lid;e<n_el;e+=wg){
    uint t=e>>log_c, col=col0+(e&(C-1u));
    uint r=row0+(t<<s0);
    uint sr=fuse_bitrev?brev(r,log_h):r;
    tile[e]=(col<w)?in[(size_t)sr*w+col]:0UL;
  }
  threadgroup_barrier(mem_flags::mem_threadgroup);
  for(uint k=1;k<=lt;k++){
    uint hl=1u<<(k-1u);
    ulong outer=gl_pow(wlens[s0+k-1u],(ulong)lo);
    for(uint b=lid;b<(n_el>>1);b+=wg){
      uint t2=b>>log_c, lc=b&(C-1u);
      uint j=t2&(hl-1u);
      uint tl=((((t2>>(k-1u))<<k)|j)<<log_c)|lc, th=tl+(hl<<log_c);
      ulong tw=gl_mul(outer,gl_pow(wlens[k-1u],(ulong)j));
      ulong u=tile[tl], v=gl_mul(tile[th],tw);
      tile[tl]=gl_add(u,v); tile[th]=gl_sub(u,v);
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
  }
  for(uint e=lid;e<n_el;e+=wg){
    uint t=e>>log_c, col=col0+(e&(C-1u));
    if(col<w){
      uint r=row0+(t<<s0);
      ulong x=tile[e];
      if(post_c!=1UL||post_b!=1UL) x=gl_mul(x,gl_mul(post_c,gl_pow(post_b,(ulong)r)));
      uint orow=store_brev?brev(r,log_h):r;
      out[(size_t)orow*w+col]=do_canon?gl_canon(x):x;
    }
  }
}
// ---- Poseidon2-Goldilocks width-8 (matches p3 `default_goldilocks_poseidon2_8`) ----
inline ulong gl_pow7(ulong x){ ulong x2=gl_mul(x,x); ulong x3=gl_mul(x2,x); ulong x4=gl_mul(x2,x2); return gl_mul(x4,x3); }
// apply_mat4 on x[0..4] (p3 external.rs; order matters — overwrite 0/2 after 1/3).
inline void mat4(thread ulong* x){
  ulong t01=gl_add(x[0],x[1]); ulong t23=gl_add(x[2],x[3]);
  ulong t0123=gl_add(t01,t23); ulong t01123=gl_add(t0123,x[1]); ulong t01233=gl_add(t0123,x[3]);
  x[3]=gl_add(t01233,gl_add(x[0],x[0]));
  x[1]=gl_add(t01123,gl_add(x[2],x[2]));
  x[0]=gl_add(t01123,t01);
  x[2]=gl_add(t01233,t23);
}
// external linear layer (mds_light_permutation, WIDTH 8): M4 per chunk, then outer circulant sums.
inline void extl(thread ulong* s){
  mat4(s); mat4(s+4);
  ulong z0=gl_add(s[0],s[4]),z1=gl_add(s[1],s[5]),z2=gl_add(s[2],s[6]),z3=gl_add(s[3],s[7]);
  s[0]=gl_add(s[0],z0); s[1]=gl_add(s[1],z1); s[2]=gl_add(s[2],z2); s[3]=gl_add(s[3],z3);
  s[4]=gl_add(s[4],z0); s[5]=gl_add(s[5],z1); s[6]=gl_add(s[6],z2); s[7]=gl_add(s[7],z3);
}
// internal linear layer (matmul_internal): s[i] = s[i]*diag[i] + sum(s).
inline void intl(thread ulong* s,device const ulong* diag){
  ulong sum=0UL; for(int i=0;i<8;i++) sum=gl_add(sum,s[i]);
  for(int i=0;i<8;i++) s[i]=gl_add(gl_mul(s[i],diag[i]),sum);
}
// full permutation: extl; 4 full (rc+x^7 all lanes, extl); 22 partial (rc+x^7 lane0, intl); 4 full.
inline void perm8(thread ulong* s,device const ulong* rci,device const ulong* rcp,device const ulong* rcf,device const ulong* diag){
  extl(s);
  for(int r=0;r<4;r++){ for(int i=0;i<8;i++) s[i]=gl_pow7(gl_add(s[i],rci[r*8+i])); extl(s); }
  for(int r=0;r<22;r++){ s[0]=gl_pow7(gl_add(s[0],rcp[r])); intl(s,diag); }
  for(int r=0;r<4;r++){ for(int i=0;i<8;i++) s[i]=gl_pow7(gl_add(s[i],rcf[r*8+i])); extl(s); }
}
// leaf hash (PaddingFreeSponge<8,4,4>): one thread per row, sponge over `w` elems, out[row*4..].
// Padding-free: overwrite state[0..4] with each block, permute after any absorbed block.
// Row-banded: `in` is a band of `band_h` rows (band-local), `out` is the full leaf-digest buffer;
// thread g hashes band row g into digest `row0+g`. Row-independent, so banding is bit-transparent.
kernel void leaf_hash(
    device const ulong* in [[buffer(0)]],
    device ulong* out [[buffer(1)]],
    constant uint& row0 [[buffer(2)]],
    constant uint& band_h [[buffer(3)]],
    constant uint& w [[buffer(4)]],
    device const ulong* rci [[buffer(5)]],
    device const ulong* rcp [[buffer(6)]],
    device const ulong* rcf [[buffer(7)]],
    device const ulong* diag [[buffer(8)]],
    uint _gid [[thread_position_in_grid]],
    uint _lid [[thread_index_in_threadgroup]],
    uint _group [[threadgroup_position_in_grid]],
    uint _gsize [[threads_per_threadgroup]]) {
  size_t g=_gid; if(g>=band_h) return;
  ulong s[8]; for(int i=0;i<8;i++) s[i]=0UL;
  device const ulong* r=in+(size_t)g*w;
  uint i=0;
  while(i<w){ for(uint k=0;k<4 && i<w;k++){ s[k]=r[i]; i++; } perm8(s,rci,rcp,rcf,diag); }
  for(int k=0;k<4;k++) out[(size_t)(row0+g)*4+k]=gl_canon(s[k]);
}
// compress one tree layer (TruncatedPermutation<2,4,8>): out[j] = trunc(perm(in[2j] || in[2j+1])).
kernel void compress_layer(
    device const ulong* in [[buffer(0)]],
    device ulong* out [[buffer(1)]],
    constant uint& n_out [[buffer(2)]],
    device const ulong* rci [[buffer(3)]],
    device const ulong* rcp [[buffer(4)]],
    device const ulong* rcf [[buffer(5)]],
    device const ulong* diag [[buffer(6)]],
    uint _gid [[thread_position_in_grid]],
    uint _lid [[thread_index_in_threadgroup]],
    uint _group [[threadgroup_position_in_grid]],
    uint _gsize [[threads_per_threadgroup]]) {
  size_t j=_gid; if(j>=n_out) return;
  ulong s[8]; for(int k=0;k<4;k++){ s[k]=in[(size_t)(2*j)*4+k]; s[4+k]=in[(size_t)(2*j+1)*4+k]; }
  perm8(s,rci,rcp,rcf,diag);
  for(int k=0;k<4;k++) out[(size_t)j*4+k]=gl_canon(s[k]);
}


kernel void retained_merkle_path(
    device const ulong *tree [[buffer(0)]],
    device ulong *output [[buffer(1)]],
    constant uint& height [[buffer(2)]],
    constant uint& index [[buffer(3)]],
    constant uint& path_len [[buffer(4)]],
    uint _gid [[thread_position_in_grid]],
    uint _lid [[thread_index_in_threadgroup]],
    uint _group [[threadgroup_position_in_grid]],
    uint _gsize [[threads_per_threadgroup]]) {
    uint level = _gid;
    if (level >= path_len) return;
    ulong rows = ((ulong)height) >> level;
    ulong preceding = 2ul * (ulong)height - 2ul * rows;
    ulong sibling = (((ulong)index) >> level) ^ 1ul;
    ulong offset = (preceding + sibling) * 4ul;
    for (uint word = 0; word < 4; ++word)
        output[level * 4 + word] = tree[offset + word];
}


// Absorb an uninterrupted column stream. A tile or matrix boundary is NOT a
// sponge boundary; only every fourth word permutes. The final partial block is
// permuted once by lde_leaf_finalize, preserving the padding-free CPU sponge.
kernel void lde_absorb(
    device const ulong *input [[buffer(0)]],
    device ulong *states [[buffer(1)]],
    constant uint& row0 [[buffer(2)]],
    constant uint& rows [[buffer(3)]],
    constant uint& width [[buffer(4)]],
    constant uint& rate_offset [[buffer(5)]],
    device const ulong *rci [[buffer(6)]],
    device const ulong *rcp [[buffer(7)]],
    device const ulong *rcf [[buffer(8)]],
    device const ulong *diag [[buffer(9)]],
    uint _gid [[thread_position_in_grid]],
    uint _lid [[thread_index_in_threadgroup]],
    uint _group [[threadgroup_position_in_grid]],
    uint _gsize [[threads_per_threadgroup]]) {
    size_t row = _gid;
    if (row >= rows) return;
    ulong s[8];
    size_t state_base = ((size_t)row0 + row) * 8;
    for (uint k = 0; k < 8; ++k) s[k] = states[state_base + k];
    uint at = rate_offset;
    for (uint col = 0; col < width; ++col) {
        s[at++] = input[row * (size_t)width + col];
        if (at == 4) { perm8(s, rci, rcp, rcf, diag); at = 0; }
    }
    for (uint k = 0; k < 8; ++k) states[state_base + k] = s[k];
}
kernel void lde_leaf_finalize(
    device const ulong *states [[buffer(0)]],
    device ulong *leaves [[buffer(1)]],
    constant uint& height [[buffer(2)]],
    constant uint& rate_offset [[buffer(3)]],
    device const ulong *rci [[buffer(4)]],
    device const ulong *rcp [[buffer(5)]],
    device const ulong *rcf [[buffer(6)]],
    device const ulong *diag [[buffer(7)]],
    uint _gid [[thread_position_in_grid]],
    uint _lid [[thread_index_in_threadgroup]],
    uint _group [[threadgroup_position_in_grid]],
    uint _gsize [[threads_per_threadgroup]]) {
    size_t row = _gid;
    if (row >= height) return;
    ulong s[8];
    for (uint k = 0; k < 8; ++k) s[k] = states[row * 8 + k];
    if (rate_offset != 0) perm8(s, rci, rcp, rcf, diag);
    for (uint k = 0; k < 4; ++k) leaves[row * 4 + k] = gl_canon(s[k]);
}
// IDFT already multiplied coefficient i by (generator / domain_shift)^i.
// This applies the same balanced hiding polynomial as CPU fused_ldes.
kernel void quotient_mask(
    device ulong *coefficients [[buffer(0)]],
    device const ulong *masks [[buffer(1)]],
    constant uint& height [[buffer(2)]],
    constant uint& width [[buffer(3)]],
    constant ulong& generator [[buffer(4)]],
    constant ulong& ratio_h [[buffer(5)]],
    uint _gid [[thread_position_in_grid]],
    uint _lid [[thread_index_in_threadgroup]],
    uint _group [[threadgroup_position_in_grid]],
    uint _gsize [[threads_per_threadgroup]]) {
    size_t index = _gid;
    size_t elements = (size_t)height * width;
    if (index >= elements) return;
    ulong masked = gl_mul(masks[index], gl_pow(generator, (ulong)(index / width)));
    coefficients[index] = gl_sub(coefficients[index], masked);
    coefficients[elements + index] = gl_mul(ratio_h, masked);
}


// Candidate extension basis: X^3 = X + 1, not the binomial cubic basis.
inline void opening_cubic_mul(thread ulong a[3], thread ulong b[3], thread ulong out[3]) {
    ulong c3 = gl_add(gl_mul(a[1], b[2]), gl_mul(a[2], b[1]));
    ulong c4 = gl_mul(a[2], b[2]);
    out[0] = gl_add(gl_mul(a[0], b[0]), c3);
    out[1] = gl_add(gl_add(gl_mul(a[0], b[1]), gl_mul(a[1], b[0])), gl_add(c3, c4));
    out[2] = gl_add(gl_add(gl_add(gl_mul(a[0], b[2]), gl_mul(a[1], b[1])), gl_mul(a[2], b[0])), c4);
}
kernel void opening_reduce(
    device const ulong *input [[buffer(0)]],
    device const ulong *weights [[buffer(1)]],
    device const ulong *denominators [[buffer(2)]],
    device const ulong *terms [[buffer(3)]],
    device ulong *output [[buffer(4)]],
    constant uint& row0 [[buffer(5)]],
    constant uint& rows [[buffer(6)]],
    constant uint& width [[buffer(7)]],
    constant uint& points [[buffer(8)]],
    uint _gid [[thread_position_in_grid]],
    uint _lid [[thread_index_in_threadgroup]],
    uint _group [[threadgroup_position_in_grid]],
    uint _gsize [[threads_per_threadgroup]]) {
    size_t row = _gid;
    if (row >= rows) return;
    ulong compressed[3] = {0, 0, 0};
    for (uint col = 0; col < width; ++col) {
        ulong value = input[row * (size_t)width + col];
        for (uint k = 0; k < 3; ++k)
            compressed[k] = gl_add(compressed[k], gl_mul(value, weights[3 * (size_t)col + k]));
    }
    ulong sum[3] = {0, 0, 0};
    for (uint point = 0; point < points; ++point) {
        ulong offset[3], delta[3], inverse[3], product[3], scaled[3];
        for (uint k = 0; k < 3; ++k) {
            offset[k] = terms[6 * point + k];
            delta[k] = gl_sub(terms[6 * point + 3 + k], compressed[k]);
            inverse[k] = denominators[(row * (size_t)points + point) * 3 + k];
        }
        opening_cubic_mul(delta, inverse, product);
        opening_cubic_mul(offset, product, scaled);
        for (uint k = 0; k < 3; ++k) sum[k] = gl_add(sum[k], scaled[k]);
    }
    for (uint k = 0; k < 3; ++k) {
        size_t at = ((size_t)row0 + row) * 3 + k;
        output[at] = gl_canon(gl_add(output[at], sum[k]));
    }
}
// Low-coset inputs are physically bit-reversed. Emit natural-order cubic
// coefficients so the existing inverse/forward NTT can extend their polynomial.
kernel void opening_compress_low(
    device const ulong *input [[buffer(0)]],
    device const ulong *weights [[buffer(1)]],
    device ulong *output [[buffer(2)]],
    constant uint& row0 [[buffer(3)]],
    constant uint& rows [[buffer(4)]],
    constant uint& width [[buffer(5)]],
    constant uint& log_low_height [[buffer(6)]],
    uint _gid [[thread_position_in_grid]],
    uint _lid [[thread_index_in_threadgroup]],
    uint _group [[threadgroup_position_in_grid]],
    uint _gsize [[threads_per_threadgroup]]) {
    size_t row = _gid;
    if (row >= rows) return;
    ulong sum[3] = {0, 0, 0};
    for (uint col = 0; col < width; ++col)
        for (uint k = 0; k < 3; ++k)
            sum[k] = gl_add(sum[k], gl_mul(input[row * (size_t)width + col],
                                         weights[3 * (size_t)col + k]));
    size_t at = (size_t)brev(row0 + (uint)row, log_low_height) * 3;
    for (uint k = 0; k < 3; ++k) output[at + k] = gl_canon(sum[k]);
}
kernel void opening_reduce_compact(
    device const ulong *compressed [[buffer(0)]],
    device const ulong *denominators [[buffer(1)]],
    device const ulong *terms [[buffer(2)]],
    device ulong *output [[buffer(3)]],
    constant uint& row0 [[buffer(4)]],
    constant uint& rows [[buffer(5)]],
    constant uint& points [[buffer(6)]],
    uint _gid [[thread_position_in_grid]],
    uint _lid [[thread_index_in_threadgroup]],
    uint _group [[threadgroup_position_in_grid]],
    uint _gsize [[threads_per_threadgroup]]) {
    size_t row = _gid;
    if (row >= rows) return;
    size_t at = ((size_t)row0 + row) * 3;
    ulong sum[3] = {0, 0, 0};
    for (uint point = 0; point < points; ++point) {
        ulong offset[3], delta[3], inverse[3], product[3], scaled[3];
        for (uint k = 0; k < 3; ++k) {
            offset[k] = terms[6 * point + k];
            delta[k] = gl_sub(terms[6 * point + 3 + k], compressed[at + k]);
            inverse[k] = denominators[(row * (size_t)points + point) * 3 + k];
        }
        opening_cubic_mul(delta, inverse, product);
        opening_cubic_mul(offset, product, scaled);
        for (uint k = 0; k < 3; ++k) sum[k] = gl_add(sum[k], scaled[k]);
    }
    for (uint k = 0; k < 3; ++k)
        output[at + k] = gl_canon(gl_add(output[at + k], sum[k]));
}

kernel void arithmetic_probe(device const ulong* a [[buffer(0)]],
    device const ulong* b [[buffer(1)]], device ulong* out [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    out[i*4] = gl_canon(gl_mul(a[i], b[i]));
    out[i*4+1] = gl_canon(gl_add(a[i], b[i]));
    out[i*4+2] = gl_canon(gl_sub(a[i], b[i]));
    out[i*4+3] = metal_mul_hi(a[i], b[i]);
}
