#!/usr/bin/env python3
"""Generate the checked-in Metal port from the shared OpenCL arithmetic.

Only this fixed, reviewed kernel set is accepted. This is a development tool;
the prover compiles the checked-in MSL, never translates source at runtime.
"""
import hashlib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FILES = ["src/gpu.rs", "src/block_v2/gpu_hash/engine.rs",
         "src/block_v2/gpu_hash/engine/lde_execute.rs",
         "src/block_v2/gpu_hash/engine/opening_reduce.rs"]
NAMES = ["KERNEL_SRC", "RETAINED_PATH_KERNEL", "KERNEL_SRC", "KERNEL_SRC"]
parts = []
for file, name in zip(FILES, NAMES):
    source = (ROOT / file).read_text()
    source = re.search(r"const " + name + r': &str = r#"(.*?)"#;', source, re.S)[1]
    if file == FILES[0]:
        source = source.split("// elementwise dst[i]")[0]
    parts.append(source)
source = "\n".join(parts)
digest = hashlib.sha256(source.encode()).hexdigest()
source = source.replace("mul_hi(a,b)", "metal_mul_hi(a,b)")
source = source.replace("__global", "device").replace("__local", "threadgroup")
source = re.sub(r"inline void (\w+)\((.*?)\)",
                lambda m: "inline void " + m[1] + "(" + re.sub(
                    r"(?<!\w)(ulong\s*\*\s*\w+|ulong\s+\w+\[\d+\])",
                    r"thread \1", m[2]) + ")", source)
# Device pointers in helper signatures already carry their address space.
source = source.replace("device const thread ulong", "device const ulong")
source = source.replace("get_global_id(0)", "_gid").replace("get_local_id(0)", "_lid")
source = source.replace("get_group_id(0)", "_group").replace("get_local_size(0)", "_gsize")
source = source.replace("barrier(CLK_LOCAL_MEM_FENCE)", "threadgroup_barrier(mem_flags::mem_threadgroup)")
kernels = []
def signature(match):
    name, args = match[1], match[2].split(",")
    kernels.append(name)
    result = []
    for index, arg in enumerate(args):
        arg = arg.strip()
        if arg.startswith("threadgroup"):
            result.append(arg + " [[threadgroup(0)]]")
        elif arg.startswith("device"):
            result.append(arg + f" [[buffer({index})]]")
        else:
            typ, variable = arg.replace("const ", "").split()
            assert typ in ("uint", "ulong"), arg
            result.append(f"constant {typ}& {variable} [[buffer({index})]]")
    result += ["uint _gid [[thread_position_in_grid]]", "uint _lid [[thread_index_in_threadgroup]]",
               "uint _group [[threadgroup_position_in_grid]]", "uint _gsize [[threads_per_threadgroup]]"]
    return "kernel void " + name + "(\n    " + ",\n    ".join(result) + ") {"
source = re.sub(r"__kernel void (\w+)\((.*?)\)\s*\{", signature, source, flags=re.S)
header = f"""// Generated by scripts/generate-metal-kernels.py. Source SHA-256: {digest}
#include <metal_stdlib>
using namespace metal;
// Full-width high product from exact 32-bit limbs. No floating-point arithmetic.
inline ulong metal_mul_hi(ulong a, ulong b) {{
    ulong p0 = ulong(uint(a)) * uint(b);
    ulong p1 = ulong(uint(a)) * uint(b >> 32);
    ulong p2 = ulong(uint(a >> 32)) * uint(b);
    ulong p3 = ulong(uint(a >> 32)) * uint(b >> 32);
    ulong carry = (p0 >> 32) + ulong(uint(p1)) + ulong(uint(p2));
    return p3 + (p1 >> 32) + (p2 >> 32) + (carry >> 32);
}}
"""
source += """
kernel void arithmetic_probe(device const ulong* a [[buffer(0)]],
    device const ulong* b [[buffer(1)]], device ulong* out [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    out[i*4] = gl_canon(gl_mul(a[i], b[i]));
    out[i*4+1] = gl_canon(gl_add(a[i], b[i]));
    out[i*4+2] = gl_canon(gl_sub(a[i], b[i]));
    out[i*4+3] = metal_mul_hi(a[i], b[i]);
}
"""
destination = ROOT / "src/metal_compute/kernels.metal"
destination.parent.mkdir(exist_ok=True)
destination.write_text(header + source)
print("Generated", destination, "kernels:", ", ".join(kernels + ["arithmetic_probe"]))
