//! Poseidon2 over Goldilocks — **the in-circuit hash**, ported to Zig so the protocol's
//! note-commitment / nullifier / Merkle hashing equals `lattica-prover-p3`'s circuit byte-for-byte
//! (audit finding C-03). Width 8, S-box x⁷, 8 full + 22 partial rounds, vetted `p3-goldilocks`
//! constants. The constants + the known-answer vectors below are generated by
//! `lattica-prover-p3 … --bin dump_p2`; the KAT tests pin equality with the circuit.
//!
//! Domain separation (matches `joinsplit_air`): a distinct tag in lane 0 of each data hash
//! (`DOM_OWN/DOM_CM/DOM_NF`); the Merkle merge is untagged (2-to-1 over digests).

const std = @import("std");
const field = @import("field.zig");
const Felt = field.Felt;

const add = field.add;
const mul = field.mul;

pub const DIGEST_FELTS: usize = 4;
pub const Digest = [DIGEST_FELTS]Felt;

// domain-separation tags (must match joinsplit_air::DOM_*)
pub const DOM_OWN: u64 = 1;
pub const DOM_CM: u64 = 2;
pub const DOM_NF: u64 = 3;
pub const DOM_HTLC: u64 = 4; // v3: htlc_root MD-chain (must match htlc_air::DOM_HTLC)
pub const DOM_NF_HTLC: u64 = 5; // v3: owner-based HTLC nullifier (must match htlc_air::DOM_NF_HTLC)
pub const DOM_TXROOT: u64 = 6; // v3 batch: per-tx statement digest in the block tx-root (must match batch_joinsplit_air)

pub const NOTE_PLAIN: u64 = 0;
pub const NOTE_HTLC: u64 = 1;

// --- vetted constants (generated; do not edit by hand — regenerate via dump_p2) ---------------
const DIAG8 = [8]u64{ 18446744069414584319, 1, 2, 9223372034707292161, 3, 9223372034707292160, 18446744069414584318, 18446744069414584317 };
const EXT_INIT = [4][8]u64{
    .{ 15949291268843349465, 14644164809401934923, 18420360874837380316, 4756469047455716334, 8685499049481102115, 3799221349720045367, 13676397835037157930, 6566439050423619635 },
    .{ 17428268347612331188, 2833135872454503769, 4767009016213040191, 2797635963551733652, 5312339450141126694, 5356668452102813289, 1234059326449530173, 7724302552453704877 },
    .{ 14868588146468890290, 12825281145595371185, 13097885453579304196, 7905326782341128063, 14167525334039893569, 2082169701994688927, 12190787523818595537, 12602917751946636 },
    .{ 14890907856876319003, 16552240149997473409, 5634093690795187558, 4883714163685656967, 12440776365164557866, 3923800234666204307, 9858064884105950259, 16040043470428402038 },
};
const EXT_FINAL = [4][8]u64{
    .{ 94277733998400326, 10891359798487446420, 18280773820738154043, 13714589910668449566, 10639034072771185213, 14148790895768484219, 18341268649720100165, 3096672942770686236 },
    .{ 12277596046563557393, 400461754528604020, 12955488253560265444, 11773677676764285572, 4833837465239476573, 17645852643693996619, 6605134696140007471, 588040525114200273 },
    .{ 11001741536026769411, 17917086578469406776, 14893530806420712543, 727997185253761138, 3443873847340254325, 13095911531247069692, 8330737046680948619, 6014364575875986011 },
    .{ 16851679856681761121, 17817965496543149594, 12823640325246269760, 13685256787930775147, 4682652317564502291, 4233879762155685988, 11097258179564187322, 10804761421745472094 },
};
const INTERNAL = [22]u64{ 5226594323142090582, 1243120476974621208, 12100812801659301173, 11228203327983058121, 13891617888374767564, 5742893160230537107, 3763472116988983643, 2466655769425769160, 6254574254498162968, 14183251225809189357, 11565357354521717084, 17300657704266685688, 310485250821938281, 16853586468012618118, 1978800426240373849, 6948188224235462572, 1486402152218690509, 5669161690283398991, 17943970877073781734, 17926851897715769433, 13052837496695000666, 18138113741095562305 };

// --- permutation -------------------------------------------------------------------------------

fn sbox(x: Felt) Felt {
    return field.pow(x, 7);
}

/// M4 applied to a 4-element chunk (matches p3 `apply_mat4`).
fn applyMat4(x: *[4]Felt) void {
    const t01 = add(x[0], x[1]);
    const t23 = add(x[2], x[3]);
    const t0123 = add(t01, t23);
    const t01123 = add(t0123, x[1]);
    const t01233 = add(t0123, x[3]);
    x[3] = add(t01233, add(x[0], x[0]));
    x[1] = add(t01123, add(x[2], x[2]));
    x[0] = add(t01123, t01);
    x[2] = add(t01233, t23);
}

/// External (light MDS) layer for width 8: M4 on each chunk, then the outer circulant sums.
fn mdsLight(s: *[8]Felt) void {
    applyMat4(s[0..4]);
    applyMat4(s[4..8]);
    var sums: [4]Felt = undefined;
    inline for (0..4) |k| sums[k] = add(s[k], s[k + 4]);
    inline for (0..8) |i| s[i] = add(s[i], sums[i % 4]);
}

/// Internal layer: `state[i] = state[i]·DIAG[i] + Σ state`.
fn internalLinear(s: *[8]Felt) void {
    var sum: Felt = 0;
    for (s) |x| sum = add(sum, x);
    inline for (0..8) |i| s[i] = add(mul(s[i], DIAG8[i]), sum);
}

fn fullRound(s: *[8]Felt, rc: [8]u64) void {
    inline for (0..8) |i| s[i] = sbox(add(s[i], rc[i]));
    mdsLight(s);
}

fn partialRound(s: *[8]Felt, rc: u64) void {
    s[0] = sbox(add(s[0], rc));
    internalLinear(s);
}

/// The Poseidon2-Goldilocks permutation (in place).
pub fn permute(state: *[8]Felt) void {
    mdsLight(state);
    for (EXT_INIT) |rc| fullRound(state, rc);
    for (INTERNAL) |rc| partialRound(state, rc);
    for (EXT_FINAL) |rc| fullRound(state, rc);
}

// --- domain-tagged hashes (match joinsplit_air) -----------------------------------------------

/// `H(domain ‖ elems)`, digest = first 4 lanes. `elems.len()` must be ≤ 7.
fn h(domain: u64, elems: []const Felt) Digest {
    var s = [_]Felt{0} ** 8;
    s[0] = domain;
    for (elems, 0..) |e, i| s[1 + i] = e;
    permute(&s);
    return s[0..4].*;
}

pub fn recipient(nk0: Felt, nk1: Felt, d: Felt) Digest {
    return h(DOM_OWN, &.{ nk0, nk1, d }); // 128-bit nullifier key + diversifier
}

/// Two-permutation commitment (128-bit note randomness; must match joinsplit_air/htlc_air::commit):
///   H1 = perm([DOM_CM, owner(4), value, rho0, rho1]); cm = perm([H1(4), rcm0, rcm1, asset, note_type]).
/// `owner` is the recipient digest (PLAIN) or the htlc_root (HTLC); `note_type` is 0 (PLAIN) / 1 (HTLC).
pub fn commitNote(owner: Digest, value: Felt, rho: [2]Felt, rcm: [2]Felt, asset: Felt, note_type: Felt) Digest {
    var a = [_]Felt{ DOM_CM, owner[0], owner[1], owner[2], owner[3], value, rho[0], rho[1] };
    permute(&a);
    var b = [_]Felt{ a[0], a[1], a[2], a[3], rcm[0], rcm[1], asset, note_type }; // lane6=asset, lane7=note_type
    permute(&b);
    return b[0..4].*;
}

pub fn nullifierHash(nk0: Felt, nk1: Felt, rho: [2]Felt, pos: Felt) Digest {
    return h(DOM_NF, &.{ nk0, nk1, rho[0], rho[1], pos });
}

/// v3 HTLC owner = `htlc_root`: domain-tagged MD-chain over the two party tags, the hashlock, and the
/// timeout (must match `htlc_air::htlc_root`). Block 0 = [DOM_HTLC,0,0,0, redeem_tag]; blocks 1-3 are
/// merge-shaped (chain ‖ data) absorbing refund_tag, hashlock, then [timeout,0,0,0].
pub fn htlcRoot(redeem_tag: Digest, refund_tag: Digest, hashlock: Digest, timeout: Felt) Digest {
    var s0 = [_]Felt{ DOM_HTLC, 0, 0, 0, redeem_tag[0], redeem_tag[1], redeem_tag[2], redeem_tag[3] };
    permute(&s0);
    var s1 = [_]Felt{ s0[0], s0[1], s0[2], s0[3], refund_tag[0], refund_tag[1], refund_tag[2], refund_tag[3] };
    permute(&s1);
    var s2 = [_]Felt{ s1[0], s1[1], s1[2], s1[3], hashlock[0], hashlock[1], hashlock[2], hashlock[3] };
    permute(&s2);
    var s3 = [_]Felt{ s2[0], s2[1], s2[2], s2[3], timeout, 0, 0, 0 };
    permute(&s3);
    return s3[0..4].*;
}

/// v3 HTLC nullifier: owner-based (mode/party-independent) — `H(DOM_NF_HTLC ‖ owner ‖ rho ‖ pos)`
/// (must match `htlc_air::nullifier_owner`).
pub fn nullifierHtlc(owner: Digest, rho: [2]Felt, pos: Felt) Digest {
    return h(DOM_NF_HTLC, &.{ owner[0], owner[1], owner[2], owner[3], rho[0], rho[1], pos });
}

/// 2-to-1 Merkle compression `H(l ‖ r)` (untagged, fills all 8 lanes).
pub fn merge(l: Digest, r: Digest) Digest {
    var s = [_]Felt{ l[0], l[1], l[2], l[3], r[0], r[1], r[2], r[3] };
    permute(&s);
    return s[0..4].*;
}

/// v3 batch: per-transaction statement digest `s_k` for the block tx-root fold (must match
/// `batch_joinsplit_air::tx_statement_digest`). MD-chain under `DOM_TXROOT`: block 0 =
/// `merge([DOM_TXROOT,0,0,0], anchor)`; then absorb each nullifier, each output commitment,
/// `[fee,mint,0,0]`, and `tx_binding` as 4-element chunks. The node folds these into the root it binds
/// in a block header (no witnesses needed).
pub fn txStatementDigest(anchor: Digest, nfs: []const Digest, out_cms: []const Digest, fee: Felt, mint: Felt, tx_binding: Digest) Digest {
    var c = merge(.{ DOM_TXROOT, 0, 0, 0 }, anchor);
    for (nfs) |nf| c = merge(c, nf);
    for (out_cms) |cm| c = merge(c, cm);
    c = merge(c, .{ fee, mint, 0, 0 });
    c = merge(c, tx_binding);
    return c;
}

/// The statement digest of a padding tile — matches `batch_joinsplit_air::dummy_sk()` (the digest of the
/// canonical 0-value dummy witness's statement). Pinned by the KAT below; the node folds it to pad a
/// block to a power-of-two tile count.
pub const DUMMY_SK: Digest = .{ 10093663321021608916, 18280800825645272076, 7712995835321977355, 5336904204250640364 };

/// v3 HTLC batch: per-HTLC-transaction statement digest — the join-split chunks plus
/// `[current_height,0,0,0]` and `redeem_hashlock` (must match `batch_htlc_air::tx_statement_digest`).
pub fn htlcTxStatementDigest(anchor: Digest, nfs: []const Digest, out_cms: []const Digest, fee: Felt, mint: Felt, tx_binding: Digest, current_height: Felt, redeem_hashlock: Digest) Digest {
    var c = merge(.{ DOM_TXROOT, 0, 0, 0 }, anchor);
    for (nfs) |nf| c = merge(c, nf);
    for (out_cms) |cm| c = merge(c, cm);
    c = merge(c, .{ fee, mint, 0, 0 });
    c = merge(c, tx_binding);
    c = merge(c, .{ current_height, 0, 0, 0 });
    c = merge(c, redeem_hashlock);
    return c;
}

/// The padding-tile digest for HTLC batches — matches `batch_htlc_air::dummy_sk()`.
pub const HTLC_DUMMY_SK: Digest = .{ 10539992321146962576, 13450880049652540131, 10286920310671709176, 6485382129692956089 };

/// Reduce up to 8 little-endian bytes to a field element (mod p).
pub fn feltLE(b: []const u8) Felt {
    var x: u64 = 0;
    var i: usize = 0;
    while (i < b.len and i < 8) : (i += 1) x |= @as(u64, b[i]) << @intCast(i * 8);
    return x % field.P;
}

/// Interpret a 32-byte hash as a 4-element digest (4 little-endian limbs, each mod p).
pub fn digestFromBytes(bytes: [32]u8) Digest {
    var d: Digest = undefined;
    inline for (0..4) |i| d[i] = feltLE(bytes[i * 8 .. i * 8 + 8]);
    return d;
}

/// Canonical little-endian bytes of a 4-element digest (the on-chain 32-byte hash).
pub fn digestBytes(d: Digest) [32]u8 {
    var out: [32]u8 = undefined;
    inline for (0..4) |i| std.mem.writeInt(u64, out[i * 8 ..][0..8], d[i], .little);
    return out;
}

// --- known-answer tests vs the Rust circuit (generated by dump_p2) -----------------------------

const testing = std.testing;

test "poseidon2: permute matches the circuit (KAT)" {
    var s = [8]Felt{ 0, 1, 2, 3, 4, 5, 6, 7 };
    permute(&s);
    const want = [8]Felt{ 147757088869797140, 9575016380710448421, 1936818598401832023, 11876560440185116837, 933995228215617535, 8686652366030325867, 8297621998173199092, 17588152731440920923 };
    try testing.expectEqual(want, s);
}

test "poseidon2: domain-tagged hashes match the circuit (KAT)" {
    const rcp = recipient(7, 70, 5);
    try testing.expectEqual(Digest{ 12117778067832875188, 10864618677725252023, 10798466789515031362, 11357075400886075001 }, rcp);
    try testing.expectEqual(Digest{ 10467251944032595743, 15951568864992726969, 686076823887839950, 2164025591647199027 }, commitNote(rcp, 1000, .{ 11, 211 }, .{ 100, 300 }, 9, 0));
    try testing.expectEqual(Digest{ 2354178473207051117, 1485123762175440172, 16578445368892662424, 12056995742034228502 }, nullifierHash(7, 70, .{ 11, 211 }, 9));
    try testing.expectEqual(Digest{ 15506260347376358782, 2994144798473533345, 1833939590059144543, 15204941819943812974 }, merge(.{ 1, 2, 3, 4 }, .{ 5, 6, 7, 8 }));
}

test "poseidon2: v3 HTLC hashing matches the circuit (KAT)" {
    const rt = Digest{ 1, 2, 3, 4 };
    const ft = Digest{ 5, 6, 7, 8 };
    const hl = Digest{ 81, 82, 83, 84 };
    const owner = htlcRoot(rt, ft, hl, 10);
    try testing.expectEqual(Digest{ 15897177719484060033, 8361144046291395814, 17600889302656618771, 11272242158371267546 }, owner);
    try testing.expectEqual(Digest{ 6647950231430050009, 7373637167084619540, 13996079761633078941, 10314879934369199903 }, commitNote(owner, 1000, .{ 11, 211 }, .{ 100, 300 }, 9, 1));
    try testing.expectEqual(Digest{ 2979738625760449383, 13574316116928341014, 8042570794412156501, 16772505299821460388 }, nullifierHtlc(owner, .{ 11, 211 }, 9));
}

test "poseidon2: v3 batch tx-statement fold matches the circuit (KAT)" {
    // seq statement 1..=26: anchor ‖ nf_0 ‖ nf_1 ‖ out_cm_0 ‖ out_cm_1 ‖ fee(21) ‖ mint(22) ‖ tx_binding.
    const anchor = Digest{ 1, 2, 3, 4 };
    const nfs = [_]Digest{ .{ 5, 6, 7, 8 }, .{ 9, 10, 11, 12 } };
    const ocs = [_]Digest{ .{ 13, 14, 15, 16 }, .{ 17, 18, 19, 20 } };
    const txb = Digest{ 23, 24, 25, 26 };
    // == batch_joinsplit_air::tx_statement_digest(&(1..=26)) (the batch_kat_dump test).
    try testing.expectEqual(
        Digest{ 16413833029060099665, 4880920211288721702, 16696557975413361240, 12647866530414313287 },
        txStatementDigest(anchor, &nfs, &ocs, 21, 22, txb),
    );
    // DUMMY_SK is pinned to batch_joinsplit_air::dummy_sk() and validated end-to-end in the real integration.
}

test "poseidon2: v3 HTLC batch tx-statement fold matches the circuit (KAT)" {
    // seq statement 1..=31: …join-split chunks… ‖ current_height(27) ‖ redeem_hashlock(28..31).
    const anchor = Digest{ 1, 2, 3, 4 };
    const nfs = [_]Digest{ .{ 5, 6, 7, 8 }, .{ 9, 10, 11, 12 } };
    const ocs = [_]Digest{ .{ 13, 14, 15, 16 }, .{ 17, 18, 19, 20 } };
    const txb = Digest{ 23, 24, 25, 26 };
    const hl = Digest{ 28, 29, 30, 31 };
    // == batch_htlc_air::tx_statement_digest(&(1..=31)) (the htlc_batch_kat_dump test).
    try testing.expectEqual(
        Digest{ 12024734340241841742, 6068874100855730733, 14239999004995857547, 2452102150457936639 },
        htlcTxStatementDigest(anchor, &nfs, &ocs, 21, 22, txb, 27, hl),
    );
}
